version: "3"

services:
  virtuoso:
    container_name: virtuoso
    image: "openlink/virtuoso-opensource-7"
    volumes:
      - virtuosodb:/database
    env_file:
      - .env
    ports:
      - 8890:8890
      - 1111:1111
  
  lode:
    container_name: lode
    build:
      context: lode/
      args:
        LODE_EXTERNAL_URL: https://lod.lucamartinelli.eu.org/lode
        WEBVOWL_EXTERNAL_URL: https://service.tib.eu/webvowl/#iri=
        USE_HTTPS: true
    ports:
      - 8080:8080
  
  lodview:
    container_name: lodview
    build:
      context: lodview/
    env_file:
      - .env
    ports:
      - 9090:8080

volumes:
  virtuosodb: