@startuml OntoIM
hide circle
hide unlinked
skinparam linetype ortho
skinparam ranksep 300
skinparam nodesep 50

!define OntoPiANode dff6ff
!define OntoPiAProperty 06c

!define OntoPiANodeEdited dff6ff

!define DemographicObservationNode f5c7a9
!define DemographicObservationProperty d1512d

!define DemographicEventNode ffdeb4
!define DemographicEventProperty df7861

!define WasteNode eddfb3
!define WasteProperty 61481c

!define OrganizationNode ffdede
!define OrganizationProperty 7a4495

!define HeritageNode ffdede
!define HeritageProperty 7a4495

!define RoadAccidentNode f2f2f2
!define RoadAccidentProperty 413f42

!define VehicleNode f2f2f2
!define VehicleProperty 413f42

!define TrafficFlowNode f2f2f2
!define TrafficFlowProperty 413f42

!define RoadSignalNode f2f2f2
!define RoadSignalProperty 413f42

!define FacilityNode c4ddff
!define FacilityProperty 0096ff

!define SchoolNode fefecc
!define SchoolProperty fdb827

!define GreenZoneNode b8f1b0
!define GreenZoneProperty 14c38e

!define HospitalNode fff
!define HospitalProperty 000

!define TransparencyNode ffc4c4
!define TransparencyProperty 850e35

' Imported objects from OntoPiA
package "OntoPiA" {
    class Thing <<owl>> #OntoPiANode

    class Entity <<l0>> #OntoPiANode
    class Activity <<l0>> #OntoPiANode
    class Location <<l0>> #OntoPiANode
    class EventOrSituation <<l0>> #OntoPiANode
    class Topic <<l0>> #OntoPiANode
    class Object <<l0>> #OntoPiANode
    class Characteristic <<l0>> #OntoPiANode
    class Collection <<l0>> #OntoPiANode
    class Agent <<l0>> #OntoPiANode

    class Address <<clvapit>> #OntoPiANode
    class City <<clvapit>> #OntoPiANode
    class StreetToponym <<clvapit>> #OntoPiANode
    class Feature <<clvapit>> #OntoPiANode
    class Country <<clvapit>> #OntoPiANode
    class Geometry <<clvapit>> #OntoPiANode

    class TimeInterval <<tiapit>> #OntoPiANode
    class TemporalEntity <<tiapit>> #OntoPiANode

    class Value <<muapit>> #OntoPiANode

    class OnlineContactPoint <<smapit>> #OntoPiANode
    class PhysicalContactPoint <<smapit>> #OntoPiANode

    class AccessCondition <<acapit>> #OntoPiANode

    class Person <<cpvapit>> #OntoPiANode
    class Family <<cpvapit>> #OntoPiANode

    class PriceSpecification <<potapit>> #OntoPiANode

    class PointOfInterest <<poiapit>> #OntoPiANode
    class MultiplePointOfInterest <<poiapit>> #OntoPiANode

    class Procedure <<pcapit>> #OntoPiANode

    class OSDFeature <<accoapit>> #OntoPiANode

    class AcademicDiscipline <<herapit>> #OntoPiANode

    class TransparencyResource <<transapit>> #OntoPiANode

    class TimeIndexedRole <<roapit>> #OntoPiANode
}

' Added an Accessible Point of Interest, a POI with online contact point, physical contact point, an organization owner and an access condition.
class Facility #FacilityNode
Facility -[#OntoPiAProperty]-> PointOfInterest : rdfs:subclassOf

Facility -[#OntoPiAProperty]-> OnlineContactPoint : smapit:hasOnlineContactPoint
Facility -[#OntoPiAProperty]-> PhysicalContactPoint : smapit:hasPhysicalContactPoint
Facility -[#OntoPiAProperty]-> AccessCondition : acapit:hasAccessCondition
Facility -[#OntoPiAProperty]-> OSDFeature : hasOfferedService
Facility -[#TransparencyProperty]-> ConcessionAct : concessedWithAct
Facility -[#HeritageProperty]-> CadastralData : hasCadastralData


package "Demographic Observations" {
    ' Demographic Observation
    ' A demographic observation can describe the demographic composition of an entity during time
    ' An example can be the number of subscribers to an event, emoployees of an organization, members of an association
    ' For a country it can be the number of citizens, weddings, deaths etc...
    ' A demo observation comes with its value and a demo prototype, which describes the type of person o family counted
    ' A demo observation can also be releated to a spatial object, which describes the spatial delimitation of the observation
    ' For example, we can count the number of males in a specific area, that can be a city, a borough, a street, etc...
    class DemographicObservation #DemographicObservationNode {
        observationValue: Integer
    }
    DemographicObservation -[#OntoPiAProperty]-> Activity : rdfs:subclassOf

    DemographicObservation -[#OntoPiAProperty]-> TemporalEntity : tiapit:hasTemporalEntity
    DemographicObservation -[#OntoPiAProperty]-> Feature : clvapit:hasSpatialCoverage
    DemographicObservation -[#OntoPiAProperty]-> Person : hasDemographicReference
    DemographicObservation -[#OntoPiAProperty]-> Family : hasDemographicReference

    class Citizens #DemographicObservationNode
    Citizens -[#DemographicObservationProperty]-> DemographicObservation : rdfs:subclassOf

    class CivilStatus #DemographicObservationNode
    CivilStatus -[#DemographicObservationProperty]-> DemographicObservation : rdfs:subclassOf

    CivilStatus -[#DemographicObservationProperty]-> CivilStatusCategory : hasCivilStatusCategory

    class CivilStatusCategory #DemographicObservationNode
    CivilStatusCategory -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    class Tourists #DemographicObservationNode
    Tourists -[#DemographicObservationProperty]-> DemographicObservation : rdfs:subclassOf

    Tourists -[#DemographicObservationProperty]-> TouristType : hasTouristType

    class TouristType <<enumerated>> #DemographicObservationNode {
        Arrival
        Presence
    }

    class Bookings #DemographicObservationNode
    Bookings -[#DemographicObservationProperty]-> DemographicObservation : rdfs:subclassOf

    class Subscribers #DemographicObservationNode
    Subscribers -[#DemographicObservationProperty]-> DemographicObservation : rdfs:subclassOf

    class Employees #DemographicObservationNode
    Employees -[#DemographicObservationProperty]-> DemographicObservation : rdfs:subclassOf

    class Members #DemographicObservationNode
    Members -[#DemographicObservationProperty]-> DemographicObservation : rdfs:subclassOf
}

package "Demographic Events" {
    ' A demo event represents a wedding, a death, a birth, offering a non aggregated view of a demo observation
    class DemographicEvent #DemographicEventNode {
        date
    }
    DemographicEvent -[#OntoPiAProperty]-> EventOrSituation : rdfs:subclassOf

    DemographicEvent -[#OntoPiAProperty]-> Person : hasDemographicReference
    DemographicEvent -[#OntoPiAProperty]-> Feature : clvapit:hasSpatialCoverage

    class CivilStatusEvent #DemographicEventNode
    CivilStatusEvent -[#DemographicEventProperty]-> DemographicEvent : rdfs:subclassOf

    CivilStatusEvent -[#DemographicObservationProperty]-> CivilStatusCategory : hasCivilStatusCategory

    class Subscriber #DemographicEventNode
    Subscriber -[#DemographicEventProperty]-> DemographicEvent : rdfs:subclassOf

    class Booking #DemographicEventNode
    Booking -[#DemographicEventProperty]-> DemographicEvent : rdfs:subclassOf
}

package "Transparency" {
    class ConcessionAct #TransparencyNode {
        actTitle: String
        actNumber: String
        paymentAmount: Float
        actDate: Date
    }
    ConcessionAct -[#OntoPiAProperty]-> Activity : rdfs:subclassOf

    ConcessionAct -[#TransparencyProperty]-> Agent : hasBeneficiary
    ConcessionAct -[#TransparencyProperty]-> ConcessionActType : hasConcessionActType
    ConcessionAct -[#TransparencyProperty]-> TransparencyResource : hasTransparencyResource
    ConcessionAct -[#TransparencyProperty]-> TimeIndexedRole : hasActReferent
    ConcessionAct -[#TransparencyProperty]-> Organization : hasOrganization

    class ConcessionActType #TransparencyNode
    ConcessionActType -[#OntoPiAProperty]-> Topic : rdfs:subclassOf
}

package "Organizations and Associations" {
    ' Organization, added end of activity, bankruptcy and liquidation, added number of empolyees, local units and heritage
    ' Added section and demograpgic classification of organization for private companies (taken from Camera di Commercio)
    ' Added an Artisan Organization with artisan Register code and date
    class Organization <<covapit>> #OrganizationNode {
        endActivityDate: Date
        bankruptcyDate: Date
        liquidationDate: Date
    }

    ' Organization --> Payment : sentPayment (see later)
    Organization -[#DemographicObservationProperty]-> Employees : hasEmployees
    Organization -[#OntoPiAProperty]-> Address : hasLocalUnitAddress
    Organization --> Heritage : hasHeritage

    Facility -[#OrganizationProperty]-> Organization : ownedBy

    class PrivateOrganization <<covapit>> #OrganizationNode
    PrivateOrganization -[#OrganizationProperty]-> Organization : rdfs:subclassOf

    PrivateOrganization -[#OrganizationProperty]-> OrganizationSection : hasOrganizationSection
    PrivateOrganization -[#OrganizationProperty]-> CompanyDemographicCategory : hasDemographicCategory

    class OrganizationSection #OrganizationNode
    OrganizationSection -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    class CompanyDemographicCategory #OrganizationNode
    CompanyDemographicCategory -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    class ArtisanOrganization #OrganizationNode {
        artisanRegisterCode
        artisanRegistrationDate: Date
    }
    ArtisanOrganization -[#OrganizationProperty]-> PrivateOrganization : rdfs:subclassOf

    ' Associations are sublclass of organizations, with referent, association category (controlled vocabulary) and members observation
    class Association #OrganizationNode {
        associationRegisterCode
        associationRegistrationDate: Date
        associationRemovalFromRegisterDate: Date
    }
    Association -[#OrganizationProperty]-> PrivateOrganization : rdfs:subclassOf

    Association -[#OntoPiAProperty]-> Person : hasReferent
    Association -[#OrganizationProperty]-> AssociationCategory : hasAssociationCategory
    Association -[#DemographicObservationProperty]-> Members : hasMembers
    Association -[#DemographicEventProperty]-> Subscriber : hasSubscriber

    class AssociationCategory #OrganizationNode
    AssociationCategory -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    ' The heritage of an organization, a collection of buildings owned by the organization. There are different types of heritage, like state owned assets, unavailable ecc...
    class Heritage #HeritageNode
    Heritage -[#OntoPiAProperty]-> Collection : rdfs:subclassOf

    Heritage -[#HeritageProperty]-> HeritageType : hasHeritageType
    Heritage -[#HeritageProperty]-> Facility : hasFacility

    class HeritageType #HeritageNode
    HeritageType -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    class CadastralData #HeritageNode {
        sheet
        map
        subordinate
    }
    CadastralData -[#OntoPiAProperty]-> Object : rdfs:subclassOf

    CadastralData -[#HeritageProperty]-> CadastralCategory : hasCadastralCategory

    class CadastralCategory #HeritageNode
    CadastralCategory -[#OntoPiAProperty]-> Topic : rdfs:subclassOf
}

' Events, added the organizer of the event and the subscribers
class Event <<cpevapit>> #OntoPiANodeEdited
Event -[#OrganizationProperty]-> Organization : isOrganizedBy
Event -[#DemographicObservationProperty]-> Subscribers : hasSubscribers
Event -[#DemographicEventProperty]-> Subscriber : hasSubscription

package "Waste Production" {
    ' Waste production
    class WasteProduction #WasteNode
    WasteProduction -[#OntoPiAProperty]-> Activity : rdfs:subclassOf

    WasteProduction -[#OntoPiAProperty]-> Value : hasValue
    WasteProduction -[#OntoPiAProperty]-> TemporalEntity : tiapit:hasTemporalEntity
    WasteProduction -[#OntoPiAProperty]-> Feature : clvapit:hasSpatialCoverage

    WasteProduction -[#WasteProperty]-> WasteCategory : hasWasteCategory

    class WasteCategory #WasteNode
    WasteCategory -[#OntoPiAProperty]-> Topic : rdfs:subclassOf
}

package "Roads and Traffic" {
    ' Road accidents
    class RoadAccident #RoadAccidentNode {
        date: DateTime
    }
    RoadAccident -[#OntoPiAProperty]-> EventOrSituation : rdfs:subclassOf

    RoadAccident -[#RoadAccidentProperty]-> RelevationUnit : detectedBy
    RoadAccident -[#OntoPiAProperty]-> Geometry : clvapit:hasGeometry
    RoadAccident -[#RoadAccidentProperty]-> Road : hasRoad
    RoadAccident -[#RoadAccidentProperty]-> WeatherCondition : hasWeatherCondition
    RoadAccident -[#RoadAccidentProperty]-> AccidentType : hasAccidentType
    RoadAccident -[#RoadAccidentProperty]-> InvolvedVehicle : hasInvolvedVehicle
    RoadAccident -[#RoadAccidentProperty]-> InvolvedPerson : hasInvolvedPerson
    RoadAccident -[#RoadAccidentProperty]-> InvolvedObstacle : hasInvolvedObstacle

    class RelevationUnit #RoadAccidentNode
    RelevationUnit -[#OntoPiAProperty]-> Agent : rdfs:subclassOf

    class Road #RoadAccidentNode {
        roadName
    }
    Road -[#OntoPiAProperty]-> Location : rdfs:subclassOf

    Road -[#OntoPiAProperty]-> Address : hasAddress
    Road -[#RoadAccidentProperty]-> RoadCategory : hasRoadCategory
    Road -[#RoadAccidentProperty]-> RoadType : hasRoadType
    Road -[#RoadAccidentProperty]-> PavementType : hasPavementType
    Road -[#RoadAccidentProperty]-> RoadContext : hasRoadContext
    Road -[#RoadAccidentProperty]-> RoadbedStatus : hasRoadbedStatus
    Road -[#RoadAccidentProperty]-> RoadSignalPresence : hasRoadSignalPresence

    class RoadCategory #RoadAccidentNode
    RoadCategory -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    class RoadType #RoadAccidentNode
    RoadType -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class PavementType #RoadAccidentNode
    PavementType -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class RoadContext #RoadAccidentNode
    RoadContext -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class RoadbedStatus #RoadAccidentNode
    RoadbedStatus -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class RoadSignalPresence #RoadAccidentNode
    RoadSignalPresence -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class WeatherCondition #RoadAccidentNode
    WeatherCondition -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class AccidentType #RoadAccidentNode
    AccidentType -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class InvolvedEntity #RoadAccidentNode
    InvolvedEntity -[#OntoPiAProperty]-> Entity : rdfs:subclassOf

    InvolvedEntity -[#RoadAccidentProperty]-> AccidentCircumstance : hasAccidentCircumstance

    class AccidentCircumstance #RoadAccidentNode
    AccidentCircumstance -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class InvolvedVehicle #RoadAccidentNode
    InvolvedVehicle -[#RoadAccidentProperty]-> InvolvedEntity : rdfs:subclassOf
    InvolvedVehicle -[#VehicleProperty]-> Vehicle : rdfs:subclassOf

    InvolvedVehicle -[#RoadAccidentProperty]-> InvolvedPerson : hasConducent
    InvolvedVehicle -[#RoadAccidentProperty]-> InvolvedPerson : hasPassenger
    InvolvedVehicle -[#RoadAccidentProperty]-> InvolvedPerson : hasFrontPassenger
    InvolvedVehicle -[#RoadAccidentProperty]-> InvolvedPerson : hasBackPassenger

    class InvolvedPerson #RoadAccidentNode
    InvolvedPerson --> InvolvedEntity : rdfs:subclassOf
    InvolvedPerson -[#OntoPiAProperty]-> Person : rdfs:subclassOf

    InvolvedPerson -[#RoadAccidentProperty]-> InvolvedPersonStatus : hasInvolvedPersonStatus

    class InvolvedPersonStatus #RoadAccidentNode
    InvolvedPersonStatus -[#OntoPiAProperty]-> Characteristic : rdfs:subclassOf

    class InvolvedObstacle #RoadAccidentNode
    InvolvedObstacle -[#RoadAccidentProperty]-> InvolvedEntity : rdfs:subclassOf

    class Vehicle #VehicleNode {
        licensePlate
        registrationYear: gYear
        brand
        model
        color
    }
    Vehicle -[#OntoPiAProperty]-> Object : rdfs:subclassOf

    Vehicle -[#VehicleProperty]-> VehicleCategory : hasVehicleCategory
    Vehicle -[#OntoPiAProperty]-> Value : hasLength
    Vehicle -[#OntoPiAProperty]-> Value : hasWidth
    Vehicle -[#OntoPiAProperty]-> Value : hasHeight
    Vehicle -[#OntoPiAProperty]-> Value : hasWeight
    Vehicle -[#OntoPiAProperty]-> Value : hasEngineDisplacement
    Vehicle -[#OntoPiAProperty]-> Country : hasRegistrationCountry

    class VehicleCategory #VehicleNode
    VehicleCategory -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    ' The road signals are point of interests with a signal value (e.g. 50 for a speed limit or the name of the destination indicated)
    class RoadSignal #RoadSignalNode {
        signalValue
        installationDate: Date
        removalDate: Date
    }
    RoadSignal -[#OntoPiAProperty]-> PointOfInterest : rdfs:subclassOf

    RoadSignal -[#RoadSignalProperty]-> RoadSignalType : hasSignalType

    ' The road signal type is a controlled vocabulary of all road signals, with a value, an image and a category
    class RoadSignalType #RoadSignalNode
    RoadSignalType -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    ' Traffic Flow observation. Added street toponym to road segment and vehicle category (controlled vocabulary)
    class TrafficFlow <<iotapit>> #TrafficFlowNode
    TrafficFlow -[#OntoPiAProperty]-> RoadSegment : iotapit:hasFeatureOfInterest
    TrafficFlow -[#TrafficFlowProperty]-> VehicleCategory : hasVehicleCategory
    TrafficFlow -[#TrafficFlowProperty]-> TrafficFlowDirection : hasTrafficFlowDirection

    class TrafficFlowDirection <<enumerated>> #TrafficFlowNode {
        In
        Out
    }

    class RoadSegment <<iotapit>> #TrafficFlowNode
    RoadSegment -[#OntoPiAProperty]-> StreetToponym : clvapit:hasStreetToponym
}

' Booking statistical data for accommodation facilities
class Accommodation <<accoapit>> #OntoPiANodeEdited
Accommodation -[#DemographicObservationProperty]-> Bookings : hasBookings
Accommodation -[#DemographicEventProperty]-> Booking : hasBooking

package "Schools" {
    ' A school can be public or private is an accessible point of interest, with services, subscribers and courses that can be offer
    class School #SchoolNode {
        schoolCode
    }
    School -[#FacilityProperty]-> Facility : rdfs:subclassOf

    School -[#SchoolProperty]-> SchoolType : hasSchoolType
    School -[#SchoolProperty]-> Course : providesCourse
    School -[#DemographicObservationProperty]-> Subscribers : hasSubscribers
    School -[#DemographicEventProperty]-> Subscriber : hasSubscription

    class ComprehensiveInstitute #SchoolNode
    ComprehensiveInstitute -[#SchoolProperty]-> School : rdfs:subclassOf
    ComprehensiveInstitute -[#OntoPiAProperty]-> MultiplePointOfInterest : rdfs:subclassOf

    ComprehensiveInstitute -[#SchoolProperty]-> School : includesSchool

    ' controlled vocabulary
    class SchoolType #SchoolNode
    SchoolType -[#OntoPiAProperty]-> Topic : rdfs:subclassOf

    class PublicSchool #SchoolNode
    PublicSchool -[#SchoolProperty]-> School : rdfs:subclassOf

    class PrivateSchool #SchoolNode
    PrivateSchool -[#SchoolProperty]-> School : rdfs:subclassOf

    ' A course organized by a school or an organization is an activity located in a classroom (phisical or online), with a price and subscribers
    class Course #SchoolNode {
        courseCode
        name
        description
        durationHours: Integer
    }
    Course -[#OntoPiAProperty]-> Activity : rdfs:subclassOf

    Course -[#OntoPiAProperty]-> TimeInterval : tiapit:atTime
    Course -[#SchoolProperty]-> Classroom : situatedInClassroom
    Course -[#OntoPiAProperty]-> PriceSpecification : hasPriceSpecification
    Course -[#DemographicObservationProperty]-> Subscribers : hasSubscribers
    Course -[#DemographicEventProperty]-> Subscriber : hasSubscription
    Course -[#OntoPiAProperty]-> AcademicDiscipline : herapit:hasAcademicDiscipline

    ' A classroom is a space where a course take place. A physical classroom has an address, a virtual classroom is associated with the service used.
    class Classroom #SchoolNode {
        name
    }
    Classroom -[#OntoPiAProperty]-> Location : rdfs:subclassOf

    class PhysicalClassroom #SchoolNode
    PhysicalClassroom -[#SchoolProperty]-> Classroom : rdfs:subclassOf

    PhysicalClassroom -[#OntoPiAProperty]-> Address : clvapit:hasAddress

    class VirtualClassroom #SchoolNode
    VirtualClassroom -[#SchoolProperty]-> Classroom : rdfs:subclassOf

    VirtualClassroom -[#SchoolProperty]-> VideoCommunicationService : usesVideoCommunicationService

    class VideoCommunicationService #SchoolNode {
        name
        serviceURL: URI
    }
    VideoCommunicationService -[#OntoPiAProperty]-> Object : rdfs:subclassOf
}

package "Green Zones" {
    ' A green zone is an accessible point of interest that can also contains plants and can has an area
    class GreenZone #GreenZoneNode
    GreenZone -[#FacilityProperty]-> Facility : rdfs:subclassOf

    GreenZone -[#OntoPiAProperty]-> Value : hasSurface
    GreenZone -[#GreenZoneProperty]-> Plant : hasPlant

    ' A plant, with the species, the common name, the born year, planted date and its status in time. The status is described as the plant health, the height and the circumference
    class Plant #GreenZoneNode {
        plantCode
        commonName
        species
        plantingDate: DateTime
        birthYear: gYear
    }
    Plant -[#OntoPiAProperty]-> PointOfInterest : rdfs:subclassOf

    Plant -[#GreenZoneProperty]-> PlantStatusInTime : hasStatusInTime

    class PlantStatusInTime #GreenZoneNode
    PlantStatusInTime -[#OntoPiAProperty]-> EventOrSituation : rdfs:subclassOf

    PlantStatusInTime -[#OntoPiAProperty]-> Value : hasHeight
    PlantStatusInTime -[#OntoPiAProperty]-> Value : hasDiameter
    PlantStatusInTime -[#GreenZoneProperty]-> PlantHealthStatus : hasHealthStatus
    PlantStatusInTime -[#OntoPiAProperty]-> TemporalEntity : tiapit:hasTemporalEntity

    class PlantHealthStatus <<enumerated>> #GreenZoneNode {
        Good
        Fair
        Bad
        Stump
        Dead
    }
}

package "Hospitals" {
    ' An hospial is an accessible point of interest with hospital departments, services, total number of beds and departments which are also described as hospitals
    class Hospital #HospitalNode {
        totalNumberOfBeds: Integer
    }
    Hospital -[#FacilityProperty]-> Facility : rdfs:subclassOf

    Hospital -[#HospitalProperty]-> HospitalDepartment : hasHospitalDepartment

    class PublicHospital #HospitalNode
    PublicHospital -[#HospitalProperty]-> Hospital : rdfs:subclassOf

    class PrivateHospital #HospitalNode
    PrivateHospital -[#HospitalProperty]-> Hospital : rdfs:subclassOf

    class HospitalDepartment #HospitalNode
    HospitalDepartment -[#HospitalProperty]-> Hospital : rdfs:subclassOf
}
@enduml